version: '2.2'
services:
  php:
    container_name: daemon_original
    build:
      context: .
      dockerfile: ./containers/php/Dockerfile
    restart: always
    ports:
     - "1337:80"
    networks:
      vpcbr:
        ipv4_address: 10.37.13.39
    extra_hosts:
     - "chongxun.gitlab.internal:10.37.13.37"
  web:
    build:
      context: .
      dockerfile: ./containers/gitlab/Dockerfile
    container_name: 'gitlab-13.10.2-ee.0-internal'
    restart: always
    hostname: '10.37.13.37'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.37.13.37'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "meomeo@gmail.com"
        gitlab_rails['smtp_password'] = "meomeo"
        gitlab_rails['smtp_domain'] = "smtp.gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['initial_root_password'] = "meomeo";
    networks:
      vpcbr:
        ipv4_address: 10.37.13.37
networks:
  vpcbr:
    external: true
    name: chongxun-network
